import { type ReactElement } from 'react';
import { PixelGrid } from './PixelGrid';
import './animations.css';
import type { ActionState, CharacterArt, CharacterSpriteProps } from './types';

const CANVAS = 64;

// Palette (20 colors). Light source upper-left.
// D = scale shadow #052e16   d = darkest scale #14532d
// g = mid scale  #166534    G = lit scale  #15803d
// l = highlight scale #22c55e
// k = belly shadow #0c0a09  K = belly base #1c1917
// y = gold hi #fbbf24       Y = gold mid #f59e0b   o = gold deep #d97706
// r = tie shadow #7f1d1d    R = tie mid #b91c1c    e = tie/red bright #dc2626
// W = white #f1f5f9         p = paper shadow #cbd5e1
// b = cigar dark #78350f    B = cigar mid #92400e
// s = smoke #94a3b8
// f = fire orange #f97316   F = fire yellow #fde047
const PALETTE: Readonly<Record<string, string>> = {
  D: '#052e16',
  d: '#14532d',
  g: '#166534',
  G: '#15803d',
  l: '#22c55e',
  k: '#0c0a09',
  K: '#1c1917',
  y: '#fbbf24',
  Y: '#f59e0b',
  o: '#d97706',
  r: '#7f1d1d',
  R: '#b91c1c',
  e: '#dc2626',
  W: '#f1f5f9',
  p: '#cbd5e1',
  b: '#78350f',
  B: '#92400e',
  s: '#94a3b8',
  f: '#f97316',
  F: '#fde047',
};

// Empty 64-char row.
const E = '.'.repeat(CANVAS);

// Pad helper: takes a body string and pads with '.' on right to exactly 64 chars.
// If body is already > 64, it is truncated (defensive — should not happen).
function r(body: string): string {
  if (body.length >= CANVAS) return body.slice(0, CANVAS);
  return body + '.'.repeat(CANVAS - body.length);
}

// ── IDLE ───────────────────────────────────────────────────────────────────
// Coiled regally facing LEFT. Tail behind curling right. Cigar in mouth,
// claws hold a stock chart paper. Monocle on left eye with chain.
const IDLE: readonly string[] = [
  E,
  E,
  r('............................................s'),
  r('...........................................s.s'),
  r('............................................s'),
  r('...........................DDDDDDDD'),
  r('..........................DdgggggggdD'),
  r('.........................DdgGGlllGGgdD'),
  r('........................DdgGlllllllGgdD'),
  r('.......................DdgGllllyyllllGdD'),
  r('......................DdgGlllyWWWyllllGdD'),
  r('.....................DdgGllyWkkkWyllllGgdD'),
  r('....................DdgGlllyWWWyllllllGgdD'),
  r('....................DgGlllllyyylllllllGggd'),
  r('...bBb..............dgGGGlllllllllllllGggdD'),
  r('...bBBb.............dgGGWWWWWGlllllllllGgdD'),
  r('...bBBb..............dGGWWWWWWGGllllllllGgdD'),
  r('....bBb...............dGGGGGGGGGgglllllGggdD'),
  r('......b................ddDDDDDDDgggggggggdD'),
  r('.......................yyyyyyyyyyyyydgggdD'),
  r('.......................yYYYYYYYYYYydgggdD'),
  r('......................dgggggggggggggggdD'),
  r('.....................dgGGGGGGGGGGGGGGGgdD'),
  r('....................dgGGlllllllllllGGGgdD'),
  r('...................dgGlllllllllllllGGGgdD'),
  r('..................dgGllllRRRRRRRRRllGGGgdD'),
  r('..................dGllllRrrrrrrrrrRlGGGgdD'),
  r('.................dgGlllReeeeeeeeeeerlGGGgdD'),
  r('.................dGllllReeeeeeeeeeerlGGGgdD'),
  r('.................dGllllReeeeeeeeeeerlGGGGgdD'),
  r('................dgGlllllReeeeeeeeerlllGGGgdD'),
  r('................dGlllllllReeeeeeerllllGGGgdD'),
  r('...............dgGllllllllRReeeeRllllllGGGgdD'),
  r('...............dGllllllllllRRRRRllllllllGGgdD'),
  r('..............dgGllllyyllllllllllllllyllllGgdD'),
  r('..............dGllllyYYyllWWWWWWWWlyYYylllGgdD'),
  r('.............dgGllllyYYylWpppppppplyYYylllGgdD'),
  r('.............dGllllllyylWpccpcppccplyyllllGggdD'),
  r('.............dGlllllllllWppcpppcppplllllllGgdD'),
  r('............dgGGlllllllyWppppeeeppplyllllllGgdD'),
  r('............dGGGlllllllyWpeppppppeplyllllllGgdD'),
  r('............dGGlllllllllWppppppppplllllllllGgdD'),
  r('...........dgGGllllllllllWWWWWWWWlllllllllllGgdD'),
  r('...........dGGllllllllllllllllllllllllllllllGgdD'),
  r('..........dgGGGllllllKKKKKKKKKKKKKKKllllllllGGgdD'),
  r('..........dGGGllllllKkkKKKKKKKKKKkkKllllllllGGgdD'),
  r('.........dgGGllllllKkkkkkKKKKKKkkkkKllllllllGGgdD'),
  r('.........dGGGlllllKkkkkkkkKKKKkkkkkkKlllllllGGgdD'),
  r('........dgGGllllllKkkkkkkkKKKKkkkkkkKlllllllGGgdD'),
  r('........dGGllllllllKkkkkkkkKKkkkkkkKlllllllllGgdD'),
  r('.......dgGGGllllllllKkkkkkkkkkkkkkKllllllllllGgdD...DDDD'),
  r('.......dGGGllllllllllKKkkkkkkkkkKKllllllllllGGgdDDdgggdD'),
  r('......dgGGGlllllllllllllKKKKKKKlllllllllllllGGgdddggGGGgdD'),
  r('......dGGGGlllllllllllllllllllllllllllllllllGGgddgGGllGgdD'),
  r('......dGGGlllllllllllllllllllllllllllllllllGGgddgGllllGgdD'),
  r('.......dGGGGlllllllllllllllllllllllllllllllGgddgGlllllGgdD'),
  r('........dGGGGGlllllllllllllllllllllllllllGGgddgGGlllllGgdD'),
  r('.........dGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGgddgGGllllllGgdD'),
  r('..........dDdDDDDDDDDDDDDDDDDDDDDDDDDDDDDDdddgGGGllllGgdD'),
  r('............................................dggGGGGGggdD'),
  r('.............................................dgggggggdDD'),
  r('..............................................ddDDDDDdD'),
  E,
  E,
];

// ── WALK ──────────────────────────────────────────────────────────────────
// Slow forward stomp: front claw raised forward, body tilted, tail swishes.
const WALK: readonly string[] = [
  E,
  r('............................................s'),
  r('...........................................s.s'),
  r('............................................s'),
  E,
  r('..........................DDDDDDDD'),
  r('.........................DdgggggggdD'),
  r('........................DdgGGlllGGgdD'),
  r('.......................DdgGlllllllGgdD'),
  r('......................DdgGllllyyllllGdD'),
  r('.....................DdgGlllyWWWyllllGdD'),
  r('....................DdgGllyWkkkWyllllGgdD'),
  r('...................DdgGlllyWWWyllllllGgdD'),
  r('...................DgGlllllyyylllllllGggd'),
  r('..bBb..............dgGGGlllllllllllllGggdD'),
  r('..bBBb.............dgGGWWWWWGlllllllllGgdD'),
  r('..bBBb..............dGGWWWWWWGGllllllllGgdD'),
  r('...bBb...............dGGGGGGGGGgglllllGggdD'),
  r('.....b................ddDDDDDDDgggggggggdD'),
  r('......................yyyyyyyyyyyyydgggdD'),
  r('......................yYYYYYYYYYYydgggdD'),
  r('.....................dgggggggggggggggdD'),
  r('....................dgGGGGGGGGGGGGGGGgdD'),
  r('...................dgGGlllllllllllGGGgdD'),
  r('..................dgGlllllllllllllGGGgdD'),
  r('.................dgGllllRRRRRRRRRllGGGgdD'),
  r('.................dGllllRrrrrrrrrrRlGGGgdD'),
  r('................dgGlllReeeeeeeeeeerlGGGgdD'),
  r('................dGllllReeeeeeeeeeerlGGGgdD'),
  r('................dGllllReeeeeeeeeeerlGGGGgdD'),
  r('...............dgGlllllReeeeeeeeerlllGGGgdD'),
  r('...............dGlllllllReeeeeeerllllGGGgdD'),
  r('..............dgGllllllllRReeeeRllllllGGGgdD'),
  r('..............dGllllllllllRRRRRllllllllGGgdD'),
  r('.............dgGllllyyllllllllllllllyllllGgdD'),
  r('.............dGllllyYYyllllllllllllyYYylllGgdD'),
  r('............dgGllllyYYyllllllllllllyYYylllGgdD'),
  r('............dGllllllyyllllllllllllllyyllllGgdD'),
  r('............dGlllllllllllllllllllllllllllllGgdD'),
  r('...........dgGGllllllKKKKKKKKKKKKKKKllllllllGgdD'),
  r('...........dGGGllllllKkkKKKKKKKKKKkkKllllllllGgdD'),
  r('..........dgGGllllllKkkkkkKKKKKKkkkkKllllllllGgdD'),
  r('..........dGGGlllllKkkkkkkkKKKKkkkkkkKlllllllGgdD'),
  r('.........dgGGllllllKkkkkkkkKKKKkkkkkkKlllllllGgdD'),
  r('.........dGGllllllllKkkkkkkkKKkkkkkkKlllllllllGgdD'),
  r('........dgGGGllllllllKkkkkkkkkkkkkkKllllllllllGgdDDDDD'),
  r('........dGGGllllllllllKKkkkkkkkkkKKllllllllllGGgdDdgggdD'),
  r('.......dgGGGlllllllllllllKKKKKKKlllllllllllllGGgddgGGGgdD'),
  r('.......dGGGGllllllllllllllllllllllllllllllllGGgddgGllGgdD'),
  r('......dgGGGlllllllllllllllllllllllllllllllllGGgddgGlllGgdD'),
  r('......dGGGGGlllllllllllllllllllllllllllllllGGgddgGllllGgdD'),
  r('.......dGGGGGGlllllllllllllllllllllllllllGGGgddgGGllllGgdD'),
  r('........dGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGgdddgGGGlllGgdD'),
  r('.........dDdDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDdddggGGGllGgdD'),
  r('..............................................dggGGGGgdD'),
  r('...................yyy.........................dgggggdDD'),
  r('..................yYYYy.........................ddDDDdD'),
  r('..................yYoYy'),
  r('...................yoy'),
  E,
  r('....................kk........kk..................kk'),
  r('...................kKKk......kKKk.................kKk'),
  r('...................kKKk......kKKk.................kKk'),
  r('....................kk........kk..................kk'),
];

// ── ATTACK ────────────────────────────────────────────────────────────────
// Roaring jaw open wide. Charts thrown forward (paper flying left ahead).
const ATTACK: readonly string[] = [
  E,
  r('....WW'),
  r('...WppW'),
  r('..WppppW'),
  r('..WpccpW'),
  r('..WpeppW'),
  r('...WppW'),
  r('....WW'),
  r('.........WW.................DDDDDDDD'),
  r('........WppW...............DdgggggggdD'),
  r('.......WppppW..............dgGGlllGGgd'),
  r('.......WpcppW.............dgGlllllllGgdD'),
  r('........WppW.............dgGllllyyllllGdD'),
  r('.........WW..............dgGlllyWWWyllllGdD'),
  r('....WW..................dgGllyWkkkWyllllGgdD'),
  r('...WppW.................dgGlllyWWWyllllllGgdD'),
  r('...WppW.................dGlllllyyylllllllGggd'),
  r('....WW.....eeee.........dgGGGlllllllllllllGggdD'),
  r('..........eeFee.........dgGGWWWWWWWWWWWWGllllGgdD'),
  r('...........eeFee........GGWWWWWWWWWWWWWWWWGGllGgdD'),
  r('..........eeFFFee.......GeeeeeeeeeeeeeeeeWWGlllGgdD'),
  r('...........eeFee........GeeeeeeeeeeeeeeeeWWGlllGgdD'),
  r('............eee..........GWWWWWWWWWWWWWWWWGgglllGgdD'),
  r('..........................dGGGGGGGGGGGggggggglllGgdD'),
  r('............................yyyyyyyyyyyyydgggGgdD'),
  r('............................yYYYYYYYYYYydggggdD'),
  r('...........................dgggggggggggggggdD'),
  r('..........................dgGGGGGGGGGGGGGGgdD'),
  r('.........................dgGlllllllllllGGGgdD'),
  r('........................dgGllllRRRRRRRllGGGgdD'),
  r('........................dGlllReeeeeeeerlGGGgdD'),
  r('........................dGlllReeeeeeeerlGGGgdD'),
  r('........................dGllllReeeeerllllGGGgdD'),
  r('........................dGlllllllRRRllllllGGgdD'),
  r('.......................dgGllllyyllllllllyyllGgdD'),
  r('.......................dGlllllyYylllllllyYylllGgdD'),
  r('......................dgGllllllyylllllllllyyllllGgdD'),
  r('......................dGlllllllllllllllllllllllllGgdD'),
  r('.....................dgGGllllKKKKKKKKKKKKKKKllllllGgdD'),
  r('....................dGGGllllKkkkKKKKKKKkkkKllllllllGgdD'),
  r('...................dgGGllllKkkkkkKKKKKKkkkkKllllllllGgdD'),
  r('..................dGGGlllKkkkkkkkKKKKkkkkkkKlllllllllGgdD'),
  r('.................dgGGlllllKkkkkkkKKKKkkkkkkKlllllllllGgdD'),
  r('................dGGGllllllKkkkkkkkKKkkkkkkKlllllllllllGgdD'),
  r('...............dgGGGlllllllKkkkkkkkkkkkkkKlllllllllllllGgdD'),
  r('...............dGGGGlllllllllKKkkkkkkkkKKllllllllllllllGgdD'),
  r('..............dgGGGGllllllllllllKKKKKKKlllllllllllllllllGgdD'),
  r('..............dGGGGGGllllllllllllllllllllllllllllllllllGgdD'),
  r('..............dGGGGGGGGGGGGlllllllllllllllllllllllllllGGGgdD'),
  r('...............dGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGgddgdD'),
  r('................dDdDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDdddgdD'),
  E,
  E,
  E,
  E,
  E,
  r('..............kk........................kk'),
  r('.............kKKk......................kKKk'),
  r('.............kKKk......................kKKk'),
  r('.............kKKk......................kKKk'),
  r('..............kk........................kk'),
  E,
  E,
  E,
];

// ── HIT ───────────────────────────────────────────────────────────────────
// Cigar dropping, monocle flying off (chain trailing), body recoiling.
const HIT: readonly string[] = [
  E,
  r('..............................................yWWy'),
  r('.............................................yWkkWy'),
  r('.............................................yWkkWy'),
  r('..............................................yWWy'),
  r('...............................................y'),
  r('..............................................y'),
  r('..............................DDDDDDDD'),
  r('...........................DDdgggggggdD'),
  r('..........................DdgGGlllGGgdD'),
  r('........................DdgGGGlllllGgdD'),
  r('.......................DdgGGlllllllllGgdD'),
  r('......................DdgGllllllllllllGgdD'),
  r('......................DgGllllllKKlllllGgdD'),
  r('.....................DgGlllllKKKKlllllGggd'),
  r('.....................dgGGGllllllllllllGggdD'),
  r('......................dgGGWWGGGlllllllGgdD'),
  r('.......................dGGGGGGGGglllllGggdD'),
  r('........................ddDDDDDDgggggggdD'),
  r('....bb...................yyyyyyyyyyyyydgdD'),
  r('...bBBb..................yYYYYYYYYYYydgddD'),
  r('...bBBb.................dgggggggggggggdD'),
  r('....bbe................dgGGGGGGGGGGGGGgdD'),
  r('....e..................dgGGlllllllllGGgdD'),
  r('......................dgGllllllllllllGGgdD'),
  r('.....................dgGllllRRRRRRRllGGgdD'),
  r('.....................dGllllRrrrrrrrrRlGGgdD'),
  r('....................dgGlllReeeeeeeerlGGGgdD'),
  r('....................dGlllReeeeeeeeerllGGGgdD'),
  r('....................dGlllReeeeeeeeerllGGGgdD'),
  r('...................dgGllllReeeeeeerlllllGGgdD'),
  r('...................dGlllllllRReeRlllllllGGgdD'),
  r('..................dgGllllllllRRRllllllllllGgdD'),
  r('..................dGlllllyyllllllllllllyllGgdD'),
  r('.................dgGllllyYYyllllllllllyYYylGgdD'),
  r('.................dGlllllyYYyllllllllllyYYylGgdD'),
  r('.................dGlllllllyylllllllllllyyllGgdD'),
  r('................dgGllllllllllllllllllllllllGgdD'),
  r('................dGllllKKKKKKKKKKKKKKKKllllllGgdD'),
  r('...............dgGllllKkkkKKKKKKKKKkkkKllllllGgdD'),
  r('...............dGlllllKkkkkkKKKKKKkkkkKlllllllGgdD'),
  r('..............dgGlllllKkkkkkkkKKKKkkkkkkKllllllGgdD'),
  r('..............dGlllllllKkkkkkkkKKkkkkkkKlllllllGgdD'),
  r('.............dgGGllllllKkkkkkkkkkkkkkkkKlllllllGGgdD'),
  r('.............dGGGGllllllKKkkkkkkkkkKKllllllllllGGgdD'),
  r('............dgGGGGGllllllllKKKKKKKllllllllllllGGGgdD'),
  r('............dGGGGGGGGGGlllllllllllllllllllllGGGGgdD'),
  r('...........dgGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGgdD'),
  r('...........dGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGgdD..DDDD'),
  r('...........dDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDdDdgggdD'),
  r('..............................................dgggggGgdD'),
  r('..............................................dggGGGGgdD'),
  r('..............................................dgGGGggdD'),
  r('..............................................dggggggdD'),
  r('...............................................dDDDDDdD'),
  r('............WWWWWWWWWWWWWW'),
  r('............WppppppppppppW'),
  r('............WppccpppccppppW'),
  r('............WppppeeeeeppppW'),
  r('............WppppppppppppppW'),
  r('............WWWWWWWWWWWWWWWW'),
  E,
  E,
  E,
];

// ── SPECIAL ───────────────────────────────────────────────────────────────
// BREATH ATTACK: fire/money breath (orange-red-gold) erupts LEFT from mouth.
const SPECIAL: readonly string[] = [
  E,
  E,
  E,
  E,
  E,
  r('...........................DDDDDDDD'),
  r('..........................DdgggggggdD'),
  r('.........................DdgGGlllGGgdD'),
  r('........................DdgGlllllllGgdD'),
  r('.......................DdgGllllyyllllGdD'),
  r('......................DdgGlllyWWWyllllGdD'),
  r('.....................DdgGllyWkkkWyllllGgdD'),
  r('....................DdgGlllyWWWyllllllGgdD'),
  r('....................DgGlllllyyylllllllGggd'),
  r('...................dgGGGlllllllllllllGggdD'),
  r('..eFFe.............dgGGWWWWWWWWWWWWWlllGgdD'),
  r('.eeFFFee...........GGWWWWWWWWWWWWWWWGGlllGgdD'),
  r('eeFFyFFee.........GeeeeeeeeeeeeeeeeWGGlllGgdD'),
  r('eeFyyyFee........GeeeeeeeeeeeeeeeeeWGGlllGgdD'),
  r('eFyyFyyFe.........GWWWWWWWWWWWWWWWWWGGGlllGgdD'),
  r('eFFyFyFFe..........GGGGGGGGGGGGGGGGGGGglllGgdD'),
  r('.eFfFfFe.................yyyyyyyyyyyyydgggGgdD'),
  r('.eeFffee.................yYYYYYYYYYYydgggGgdD'),
  r('..eeFee.................dgggggggggggggggdD'),
  r('...efe.................dgGGGGGGGGGGGGGGGgdD'),
  r('....e.................dgGGlllllllllllGGGgdD'),
  r('.....................dgGlllllllllllllGGGgdD'),
  r('....................dgGllllRRRRRRRRRllGGGgdD'),
  r('....................dGllllRrrrrrrrrrRlGGGgdD'),
  r('...................dgGlllReeeeeeeeeeerlGGGgdD'),
  r('...................dGllllReeeeeeeeeeerlGGGgdD'),
  r('...................dGllllReeeeeeeeeeerlGGGGgdD'),
  r('..................dgGlllllReeeeeeeeerlllGGGgdD'),
  r('..................dGlllllllReeeeeeerllllGGGgdD'),
  r('.................dgGllllllllRReeeeRllllllGGGgdD'),
  r('.................dGllllllllllRRRRRllllllllGGgdD'),
  r('................dgGllllyyllllllllllllllyllllGgdD'),
  r('................dGllllyYYyllllllllllllyYYylllGgdD'),
  r('...............dgGllllyYYyllllllllllllyYYylllGgdD'),
  r('...............dGllllllyyllllllllllllllyyllllGgdD'),
  r('..............dgGGllllllllllllllllllllllllllllGgdD'),
  r('..............dGGGllllllKKKKKKKKKKKKKKKllllllllGgdD'),
  r('.............dgGGllllllKkkkKKKKKKKKKkkkKllllllllGgdD'),
  r('.............dGGGlllllKkkkkkKKKKKKkkkkKlllllllllGgdD'),
  r('............dgGGGlllllKkkkkkkkKKKKkkkkkkKllllllllGgdD'),
  r('............dGGGlllllllKkkkkkkkKKkkkkkkKlllllllllGgdD'),
  r('...........dgGGGGllllllKkkkkkkkkkkkkkkkKllllllllllGgdD'),
  r('...........dGGGGGGllllllKKkkkkkkkkkKKlllllllllllllGgdD'),
  r('..........dgGGGGGGGlllllllKKKKKKKllllllllllllllllllGgdD..DD'),
  r('..........dGGGGGGGGGGlllllllllllllllllllllllllllllGGgdddggdD'),
  r('..........dGGGGGGGGGGGGGGGlllllllllllllllllllllllGGGgddgGgdD'),
  r('...........dGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGggddgGGgdD'),
  r('............dDdDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDdddgGGGgdD'),
  r('...............................................dggGGGGGgdD'),
  r('................................................dgggggggdD'),
  r('.................................................dDDDDDdD'),
  E,
  r('..............kk........................kk'),
  r('.............kKKk......................kKKk'),
  r('.............kKKk......................kKKk'),
  r('.............kKKk......................kKKk'),
  r('..............kk........................kk'),
  E,
  E,
];

// ── DEFEAT ────────────────────────────────────────────────────────────────
// Collapsed sideways on ground. Monocle cracked. Charts strewn around.
const DEFEAT: readonly string[] = [
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  E,
  r('...........................................DDDDDDDDD'),
  r('..........................................DdGGGGGGGGdD'),
  r('.........................................dgGGGGGGGGGGgdD'),
  r('........................................dGGGGGGGGGGGGGgdD'),
  r('...DDDD................................dGGGGGGGGGGGGGGGgdD'),
  r('..DdggdD..............................dGGGGGGGGGGGGGGGGGgdD'),
  r('.DdgGGgdD............................dGGlllllllllllllllGGgdD'),
  r('DdgGlllGdD.........................dgGGlllllllllllllllllGGgdD'),
  r('DgGlllllGgdD......................dGGGllllKKKKKKKKKKKllllGGgdD'),
  r('dGllllKKllGgdD..................dgGGGllllKkkkKKKKKkkkKlllGGgdD'),
  r('dGllllyWyllGgdD................dGGGGlllllKkkkkkKKKKkkkkKllGGgD'),
  r('dGGllyWkW.lGgdD..............dgGGGGllllllKkkkkkkKKkkkkkkKllGgD'),
  r('dGGGllyWyllGggdD............dGGGGGGlllllllKkkkkkkKkkkkkkKllGgD'),
  r('.dGGGGGyyGGggdDD..........dGGGGGGGGGlllllllKkkkkkkkkkkkKllllgD'),
  r('..bbB...dgGGggdDD........dGGGGGGGGGGGGlllllllKKkkkkkKKllllllgD'),
  r('..bBb...ddDDDdDD........dGGGGGGGGGGGGGGlllllllllKKKlllllllllgD'),
  r('...e....................dGGGGGGGGGGGGGGGGGGGGlllllllllllllllD'),
  r('........................dDdDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD'),
  E,
  r('...WWWW.................................WWWWWW.....WWWW'),
  r('..WppppW...............................WpppppppW..WpppppW'),
  r('..WpccpW...............................WpcccccccW.WpccccpW'),
  r('..WpeppW...............................WpppeppppW.WpepppW'),
  r('..WppppW...............................WppppppppW.WpppppW'),
  r('...WWWW.................................WWWWWWWWW..WWWWW'),
  E,
  r('.................................................WWWW'),
  r('................................................WppppW'),
  r('................................................WpcppW'),
  r('................................................WppeppW'),
  r('.................................................WppppW'),
  r('..................................................WWWW'),
  E,
  E,
  r('....yy..............................................yy'),
  r('...yYYy.............................................yYYy'),
  r('....yy..............................................yy'),
  E,
  E,
  E,
  E,
];

const POSES: Record<ActionState, readonly string[]> = {
  idle: IDLE,
  walk: WALK,
  attack: ATTACK,
  hit: HIT,
  special: SPECIAL,
  defeat: DEFEAT,
};

function CeoDragonSprite({ state, size = 240 }: CharacterSpriteProps): ReactElement {
  const rows = POSES[state] ?? POSES.idle;
  return (
    <svg
      className={`cs-root cs-state-${state} cs-boss`}
      width={size}
      height={size}
      viewBox={`0 0 ${CANVAS} ${CANVAS}`}
      style={{ overflow: 'visible' }}
    >
      <PixelGrid rows={rows} palette={PALETTE} />
    </svg>
  );
}

const character: CharacterArt = {
  meta: {
    id: 'ceo-dragon',
    name: 'CEO 巨龍',
    englishName: 'CEO Dragon',
    role: 'job-hunting',
    tier: 'boss',
    topic: 'job-hunting',
    description: '穿西裝戴單片眼鏡、抽雪茄、抓股票圖表的 CEO 巨龍。',
  },
  Sprite: CeoDragonSprite,
};
export default character;
